
WITH CTE_PAGAMENTOS AS (
    -- Aqui consolidamos o financeiro por CLIENTE primeiro
    SELECT 
        C.ID_UNICO_CLIENTE,
        SUM(P.VALOR_PAGAMENTO) AS VALOR_TOTAL_REAL,
        AVG(P.QTD_PARCELAS) AS MEDIA_PARCELAS_REAL,
        COUNT(CASE WHEN P.TIPO_PAGAMENTO = 'credit_card' THEN 1 END) AS QTD_CREDITO,
        COUNT(CASE WHEN P.TIPO_PAGAMENTO = 'boleto' THEN 1 END) AS QTD_BOLETO,
        COUNT(CASE WHEN P.TIPO_PAGAMENTO = 'voucher' THEN 1 END) AS QTD_VOUCHER,
        COUNT(CASE WHEN P.TIPO_PAGAMENTO = 'debit_card' THEN 1 END) AS QTD_DEBITO
    FROM ANALYTICS.TB_DIM_CUSTOMERS C
   LEFT  JOIN ANALYTICS.TB_FAT_ORDERS O ON O.ID_CLIENTE_PEDIDO = C.ID_PEDIDO_CLIENTE
   LEFT JOIN ANALYTICS.TB_FAT_ORDER_PAYMENTS P ON P.PEDIDO_ID = O.ID_PEDIDO
    GROUP BY 1
),
CTE_ITENS AS (
    -- SUA NOVA ESTAÇÃO DE PRODUTOS E LOGÍSTICA (BASEADA NA IMAGEM QUE VOCÊ MANDOU)
    SELECT 
        C.ID_UNICO_CLIENTE,
        SUM(I.VALOR_FRETE) AS TOTAL_FRETE_PAGO,
        AVG(I.VALOR_ITEM) AS TICKET_MEDIO_PRODUTO,
        SUM(I.VALOR_ITEM) AS VALOR_TOTAL_PRODUTOS, -- VALOR SEM O FRETE
        COUNT(I.ITEM_SEQUENCIAL) AS TOTAL_ITENS_COMPRADOS,
        COUNT(DISTINCT PR.CATEGORIA_NOME) AS QTD_CATEGORIAS_DISTINTAS,
        COUNT(DISTINCT S.ID_VENDEDOR) AS QTD_VENDEDORES_DISTINTOS,
        MAX(S.UF_VENDEDOR) AS UF_PRINCIPAL_VENDEDOR -- De onde vêm a maioria das compras dele
    FROM ANALYTICS.TB_DIM_CUSTOMERS C
   LEFT  JOIN ANALYTICS.TB_FAT_ORDERS O ON O.ID_CLIENTE_PEDIDO = C.ID_PEDIDO_CLIENTE
   LEFT JOIN ANALYTICS.TB_FAT_ORDER_ITEMS I ON I.PEDIDO_ID = O.ID_PEDIDO
   LEFT JOIN ANALYTICS.TB_DIM_PRODUCTS PR ON PR.ID_PRODUTO = I.PRODUTO_ID
   LEFT JOIN ANALYTICS.TB_DIM_SELLERS S ON S.ID_VENDEDOR = I.VENDEDOR_ID
    GROUP BY 1
    )
SELECT 
-- IDENTIFICAÇÃO DO CLIENTE
C.ID_UNICO_CLIENTE AS CLIENTE,
-- Localização (com MAX para garantir 1 linha)
MAX(C.CIDADE) AS CIDADE,
MAX(C.ESTADO) AS ESTADO,
MAX(C.CEP_PREFIXO) AS CEP,
MAX(G.LATITUDE) AS LATITUDE,
MAX(G.LONGITUDE) AS LONGITUDE,
-- MÉTRICAS DE VOLUME E FREQUÊNCIA (O "F" DO RFM)
COUNT (distinct O.ID_CLIENTE_PEDIDO) AS QTD_REGISTROS_COMPRAS,
COUNT(CASE WHEN O.STATUS_PEDIDO = 'entregue' THEN 1 END) AS QTD_ENTREGUE,
-- MÉTRICA DE RECÊNCIA (O "R" DO RFM)
MAX (O.data_compra) as DATA_ULTIMA_COMPRA,
-- MÉTRICAS DE PERFORMANCE LOGÍSTICA (EXPERIÊNCIA DO CLIENTE)
ROUND(AVG(CASE WHEN O.STATUS_PEDIDO = 'entregue' THEN O.DIAS_PARA_ENTREGA END)::NUMERIC, 1) AS MEDIA_DIAS_ENTREGA,
ROUND(AVG(CASE WHEN O.STATUS_PEDIDO = 'entregue' THEN O.DIAS_ATRASO END)::NUMERIC, 1) AS MEDIA_DIAS_ATRASOSO,
-- MÉTRICAS FINANCEIRAS E DE PAGAMENTO (O "M" DO RFM + PERFIL DE CRÉDITO)
ROUND(MAX(PAG.VALOR_TOTAL_REAL)::NUMERIC, 2) AS VALOR_TOTAL_PAGO,
ROUND(MAX(PAG.MEDIA_PARCELAS_REAL)::NUMERIC, 1) AS MEDIA_PARCELAS,
-- MÉTODOS DE PAGAMENTO (Contagem de uso por tipo)
COALESCE(MAX(PAG.QTD_CREDITO), 0) AS PAG_CREDITO,
COALESCE(MAX(PAG.QTD_BOLETO), 0) AS PAG_BOLETO,
COALESCE(MAX(PAG.QTD_VOUCHER), 0) AS PAG_VOUCHER,
COALESCE(MAX(PAG.QTD_DEBITO), 0) AS PAG_DEBITO,
-- SATISFAÇÃO E ENGAJAMENTO (Vindo da sua imagem)
ROUND(AVG(R.NOTA_PONTUACAO)::NUMERIC, 1) AS MEDIA_NOTA_REVIEW,
SUM(R.FL_CLIENTE_ENGAJADO) AS TOTAL_INTERACOES_REVIEW,
-- NOVAS CARACTERÍSTICAS DE ITENS E LOGÍSTICA
COALESCE(ROUND(MAX(IT.VALOR_TOTAL_PRODUTOS)::NUMERIC, 2), 0) AS VALOR_LIQUIDO_PRODUTOS,
COALESCE(ROUND(MAX(IT.TOTAL_FRETE_PAGO)::NUMERIC, 2), 0) AS GASTO_TOTAL_FRETE,
COALESCE(MAX(IT.TOTAL_ITENS_COMPRADOS), 0) AS QTD_TOTAL_ITENS,
COALESCE(ROUND(MAX(IT.TICKET_MEDIO_PRODUTO)::NUMERIC, 2), 0) AS MEDIA_PRECO_ITEM,
COALESCE(MAX(IT.QTD_CATEGORIAS_DISTINTAS), 0) AS DIVERSIDADE_CATEGORIAS,
COALESCE(MAX(IT.QTD_VENDEDORES_DISTINTOS), 0) AS QTD_VENDEDORES_DISTINTOS,
MAX(IT.UF_PRINCIPAL_VENDEDOR) AS UF_PRINCIPAL_VENDEDOR
FROM ANALYTICS.TB_DIM_CUSTOMERS C 
LEFT JOIN ANALYTICS.TB_FAT_ORDERS O ON  O.ID_CLIENTE_PEDIDO = C.ID_PEDIDO_CLIENTE
LEFT JOIN CTE_PAGAMENTOS PAG ON PAG.ID_UNICO_CLIENTE = C.ID_UNICO_CLIENTE
LEFT JOIN CTE_ITENS IT ON IT.ID_UNICO_CLIENTE = C.ID_UNICO_CLIENTE
LEFT JOIN ANALYTICS.TB_FAT_ORDER_REVIEWS R ON R.ID_PEDIDO  = O.ID_PEDIDO 
LEFT JOIN ANALYTICS.TB_DIM_GEOLOCATION G ON G.CEP_PREFIXO = C.CEP_PREFIXO
GROUP BY  
C.ID_UNICO_CLIENTE


-- TOTAL DE CLIENTES 96.096


